# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs: 
  build:
    docker: 
      - image: gridlabd/slac-master:latest
    steps: 
      - checkout 
      - run: 
          name: Make sure Python 3.6 is properly setup
          command: |
            sudo apt-get install software-properties-common python-software-properties --yes
            sudo add-apt-repository -y ppa:deadsnakes/ppa
            sudo apt update
            sudo apt-get install python3-dev
            sudo apt install python3.6            
            sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1
            sudo update-alternatives --set python /usr/bin/python3.6            
      - run:
          name: Get Pip and install Python Dependencies
          command: |
            sudo apt-get -y install python3-pip
            sudo pip3 install matplotlib
      - run: 
          name: Run version check
          command: |
            gridlabd --version
            gridlabd --origin
      - run:
          name: Run the simulation
          command: |
            gridlabd --version
            echo "Model finished"
            git clone https://github.com/dchassin/gridlabd.git
            mv -f config/local.glm gridlabd/models/ieee123/config/
            cd gridlabd/models/ieee123
            gridlabd model/ieee123.glm
      - store_artifacts: 
            path: /root/project/gridlabd/models/ieee123/output
          
