# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2
jobs: 
  build:
    docker: 
      - image: gridlabd/slac-master:latest
    steps: 
      - checkout 
      - run: 
          name: Python install 
          command: |
            python --version
            yum -y update
            yum -y install wget
            yum -y install gcc openssl-devel bzip2-devel
            wget https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tgz
            tar xzf Python-3.7.2.tgz
            ls
            cd Python-3.7.2
            ./configure --enable–optimizations
            make altinstall
            python3.7 –v
            alias python3=python3.7
            python --version
            python3 --version
      - run: 
          name: Run version check
          command: |
            gridlabd --version
            gridlabd --origin
      - run:
          name: Run the simulation
          command: |
            gridlabd --version
            git clone https://github.com/dchassin/gridlabd.git
            mv -f config/local.glm gridlabd/models/ieee123/config/
            more gridlabd/models/ieee123/config/local.glm
            cd gridlabd/models/ieee123
            git checkout aivanova/voltdump_py_fix
            gridlabd model/ieee123.glm
      - store_artifacts: 
            path: /root/project/gridlabd/models/ieee123/output
          
