version: 2.1
jobs:
  build:
    docker:
      - image: gridlabd/slac-master
    steps:
      - checkout
      - run:
        name: Run the simulation
        command: |
          gridlabd --version
          gridlabd --origin

