version: 2
jobs:
  build:
    docker:
    - image: gridlabd/slac-master
    steps:
    - checkout
    - run:
        name: Fix the image weirdness
        command: |
          yum -y install https://centos7.iuscommunity.org/ius-release.rpm
    - run:
        name: Run the simulation
        command: |
          gridlabd --version
    - store_artifacts:
        path: /root/project
workflows:
  version: 2
  workflow:
    jobs:
    - build
          
