# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs: 
  build:
    docker: 
      - image: gridlabd/slac-master:latest
    steps: 
      - checkout 
      - run: 
          name: Run version check
          command: |
            gridlabd --version
            gridlabd --origin
      - run:
          name: Run the simulation
          command: |
            gridlabd --version
            echo "Model finished"
            git clone https://github.com/dchassin/gridlabd.git
            mv -f config/local.glm gridlabd/models/ieee123/config/
            cd gridlabd/models/ieee123
            gridlabd model/ieee123.glm
